export const COMPANY_FORM_TYPES = {
  SUBMIT: 'SUBMIT',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
};

export const COMPANIES_TYPES = {
  REQUEST: 'REQUEST',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  PUT: 'PUT',
};
